global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend-api'
    static_configs:
      - targets: ['10.0.3.91:5000']
    metrics_path: /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.3.91:9100']

rule_files:
  - "alert_rules.yml"
