---
- name: "Debug: Print message to confirm role tasks are executed"
  debug:
    msg: "backend-api role tasks are executed."

- name: Update apt cache and install prerequisites
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - unzip
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine and related packages
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

##############################
# Nomad Installation & Configuration
##############################
- name: Download Nomad zip archive (v1.9.5)
  get_url:
    url: "https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip"
    dest: "/tmp/nomad.zip"
    mode: "0644"

- name: Unarchive Nomad binary to /usr/local/bin
  unarchive:
    src: "/tmp/nomad.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
    creates: "/usr/local/bin/nomad"

- name: Ensure Nomad binary is executable
  file:
    path: /usr/local/bin/nomad
    mode: "0755"

- name: Create Nomad configuration directory
  file:
    path: /etc/nomad
    state: directory
    mode: "0755"

- name: Create Nomad data directory
  file:
    path: /opt/nomad
    state: directory
    mode: "0755"

- name: Create Nomad configuration file
  copy:
    dest: /etc/nomad/nomad.hcl
    content: |
      data_dir  = "/opt/nomad"
      bind_addr = "0.0.0.0"

      server {
        enabled           = true
        bootstrap_expect  = 1
      }
      client {
        enabled = true
      }
    mode: "0644"

- name: Create Nomad systemd service file
  copy:
    dest: /etc/systemd/system/nomad.service
    content: |
      [Unit]
      Description=Nomad Agent
      Documentation=https://www.nomadproject.io/docs/
      After=network-online.target
      Wants=network-online.target

      [Service]
      ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: yes

- name: Start and enable Nomad service
  systemd:
    name: nomad
    state: started
    enabled: yes
  become: yes

#########################
# Consul Installation & Configuration
#########################

- name: Set Consul version
  set_fact:
    consul_version: "1.9.0"

- name: Download Consul zip archive
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/tmp/consul.zip"
    mode: '0644'

- name: Unarchive Consul binary to /usr/local/bin
  unarchive:
    src: "/tmp/consul.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    creates: "/usr/local/bin/consul"

- name: Ensure Consul binary is executable
  file:
    path: /usr/local/bin/consul
    mode: '0755'

- name: Create Consul configuration directory
  file:
    path: /etc/consul
    state: directory
    mode: '0755'

- name: Create Consul data directory
  file:
    path: /opt/consul
    state: directory
    mode: '0755'

- name: Create Consul configuration file for client node
  copy:
    dest: /etc/consul/consul.hcl
    content: |
      data_dir  = "/opt/consul"
      bind_addr = "0.0.0.0"
      server    = false
      # To join an existing Consul server, specify its IP address (or a list of addresses)
      retry_join = ["10.0.3.161"]
    mode: '0644'

- name: Create Consul systemd service file
  copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul Agent
      After=network-online.target
      Wants=network-online.target

      [Service]
      ExecStart=/usr/local/bin/consul agent -config-file=/etc/consul/consul.hcl
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
